
##----------------------------------------------------------------------------##
## Global Tags                                                                ##
##----------------------------------------------------------------------------##

[global_tags]
	type = "kvrocks"
	kvrocks_cluster_name = "${AWS_TAG_KVROCKS_CLUSTER_NAME}"

##----------------------------------------------------------------------------##
## Prometheus Client                                                   Output ##
##----------------------------------------------------------------------------##

# Configuration for the Prometheus client to spawn
[[outputs.prometheus_client]]
	# Address to listen on
	listen = ":9273"

	# Mapping from Prometheus to Telegraf metrics
	metric_version = 2

	# Export metric collection time
	export_timestamp = true

	collectors_exclude = ["gocollector", "process"]

##----------------------------------------------------------------------------##
## Disk                                                                 Input ##
##----------------------------------------------------------------------------##

# Read metrics about disk usage by mount point
[[inputs.disk]]
	# Gather stats for only these mount points
	mount_points = [ "/mnt/disk" ]

	# Ignore mount points by filesystem type
	ignore_fs = [ "tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs" ]


##----------------------------------------------------------------------------##
## Exec                                                                 Input ##
##----------------------------------------------------------------------------##

# Read metrics from one or more commands that can output to stdout
[[inputs.exec]]
	commands = [
		"/etc/telegraf/service.sh --service envoy,telegraf,sshd",
		"/etc/telegraf/version.sh --service envoy,telegraf"
	]

	## Timeout for each command
	timeout = "5s"

	## Data format to consume
	data_format = "influx"

# Read metrics from one or more commands that can output to stdout
[[inputs.exec]]
	commands = [
		"/etc/telegraf/ebs_metrics.sh /dev/sdb",
	]

	## Timeout for each command
	timeout = "5s"

	## Data format to consume
	data_format = "prometheus"


##----------------------------------------------------------------------------##
## Prometheus                                                           Input ##
##----------------------------------------------------------------------------##

# Read metrics from various Prometheus clients
[[inputs.prometheus]]
	# An array of urls to scrape metrics from
	urls = [
		"http://0.0.0.0:9121/metrics"
	]

	# Mapping from Prometheus to Telegraf metrics
	metric_version = 2


[[inputs.http_listener_v2]]
	# Override metric names to avoid collisions
	name_override = "kvrocks-byron-load-test"

	## Address and port to host HTTP listener on
	service_address = ":9201"
	methods = ["GET"]

	## Paths to listen to.
	paths = ["/metrics"]

	## Data format to consume.
	data_format = "prometheus"

