[load_nodes]
nats-staging-2-1.ap-southeast-1a ansible_host=127.0.0.1 ansible_port=12755
nats-staging-2-2.ap-southeast-1a ansible_host=127.0.0.1 ansible_port=11748
nats-staging-2-3.ap-southeast-1a ansible_host=127.0.0.1 ansible_port=13278

; nats-staging-2-1.eu-central-1a ansible_host=127.0.0.1 ansible_port=13389
; nats-staging-2-2.eu-central-1a ansible_host=127.0.0.1 ansible_port=11979
; nats-staging-2-3.eu-central-1a ansible_host=127.0.0.1 ansible_port=13362
;
; nats-staging-2-1.us-east-1a ansible_host=127.0.0.1 ansible_port=12608
; nats-staging-2-2.us-east-1a ansible_host=127.0.0.1 ansible_port=12438
; nats-staging-2-3.us-east-1a ansible_host=127.0.0.1 ansible_port=12304
;
; nats-staging-2-1.us-west-1a ansible_host=127.0.0.1 ansible_port=12927
; nats-staging-2-2.us-west-1a ansible_host=127.0.0.1 ansible_port=12772
; nats-staging-2-3.us-west-1a ansible_host=127.0.0.1 ansible_port=12771

[load_nodes:vars]
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PreferredAuthentications=publickey,password -o PubkeyAuthentication=yes'
ansible_scp_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_sftp_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

# for debugging
# ANSIBLE_DEBUG=1 ansible -i ansible-load-nodes.ini load_nodes -a "echo hello"
