[load_nodes]
; nats-staging-2-1.ap-southeast-1a ansible_host=127.0.0.1 ansible_port=12755
; nats-staging-2-2.ap-southeast-1a ansible_host=127.0.0.1 ansible_port=11748
; nats-staging-2-3.ap-southeast-1a ansible_host=127.0.0.1 ansible_port=13278

; nats-staging-2-1.eu-central-1a ansible_host=127.0.0.1 ansible_port=13389
; nats-staging-2-2.eu-central-1a ansible_host=127.0.0.1 ansible_port=11979
; nats-staging-2-3.eu-central-1a ansible_host=127.0.0.1 ansible_port=13362
;
; nats-staging-2-1.us-east-1a ansible_host=127.0.0.1 ansible_port=12608
; nats-staging-2-2.us-east-1a ansible_host=127.0.0.1 ansible_port=12438
; nats-staging-2-3.us-east-1a ansible_host=127.0.0.1 ansible_port=12304
;
nats-staging-2-1.us-west-1a ansible_host=127.0.0.1 ansible_port=12927
nats-staging-2-2.us-west-1a ansible_host=127.0.0.1 ansible_port=12772
nats-staging-2-3.us-west-1a ansible_host=127.0.0.1 ansible_port=12771

; nats-fiber servers
; nats-fiber-5.ap-southeast-1a ansible_host=127.0.0.1 ansible_port=13110
; nats-fiber-6.ap-southeast-1a ansible_host=127.0.0.1 ansible_port=13115
; nats-fiber-7.ap-southeast-1a ansible_host=127.0.0.1 ansible_port=13112
; nats-fiber-read-1.ap-southeast-1a ansible_host=127.0.0.1 ansible_port=10153
; nats-fiber-read-2.ap-southeast-1a ansible_host=127.0.0.1 ansible_port=11934
; nats-fiber-read-3.ap-southeast-1a ansible_host=127.0.0.1 ansible_port=11166
;
; nats-fiber-5.eu-central-1a ansible_host=127.0.0.1 ansible_port=11723
; nats-fiber-6.eu-central-1a ansible_host=127.0.0.1 ansible_port=11937
; nats-fiber-7.eu-central-1a ansible_host=127.0.0.1 ansible_port=10734
; nats-fiber-read-1.eu-central-1a ansible_host=127.0.0.1 ansible_port=10518
; nats-fiber-read-2.eu-central-1a ansible_host=127.0.0.1 ansible_port=11116
; nats-fiber-read-3.eu-central-1a ansible_host=127.0.0.1 ansible_port=10628
;
; nats-fiber-4.us-east-1a ansible_host=127.0.0.1 ansible_port=10259
; nats-fiber-5.us-east-1a ansible_host=127.0.0.1 ansible_port=12094
; nats-fiber-6.us-east-1a ansible_host=127.0.0.1 ansible_port=12629
; nats-fiber-read-1-1.us-east-1a ansible_host=127.0.0.1 ansible_port=10322
; nats-fiber-read-1-2.us-east-1a ansible_host=127.0.0.1 ansible_port=11574
; nats-fiber-read-1-3.us-east-1a ansible_host=127.0.0.1 ansible_port=10161
;
; nats-fiber-4.us-west-1a ansible_host=127.0.0.1 ansible_port=13117
; nats-fiber-5.us-west-1a ansible_host=127.0.0.1 ansible_port=10456
; nats-fiber-6.us-west-1a ansible_host=127.0.0.1 ansible_port=10093
; nats-fiber-read-1.us-west-1a ansible_host=127.0.0.1 ansible_port=11783
; nats-fiber-read-2.us-west-1a ansible_host=127.0.0.1 ansible_port=13410
; nats-fiber-read-3.us-west-1a ansible_host=127.0.0.1 ansible_port=11650

[load_nodes:vars]
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PreferredAuthentications=publickey,password -o PubkeyAuthentication=yes'
ansible_scp_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_sftp_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

# for debugging
# ANSIBLE_DEBUG=1 ansible -i ansible-load-nodes.ini load_nodes -a "echo hello"
