---
# Usage: ansible-playbook -i ../ansible-load-nodes.ini copy-service-file.yml
# Or from parent directory: ansible-playbook -i ansible-load-nodes.ini playbooks/copy-service-file.yml
- name: Copy reader-redis service to nodes 5-9
  hosts: load_nodes_redis
  become: true
  tasks:
    - name: Copy reader-redis service to remote hosts
      ansible.builtin.copy:
        src: /Users/byron.seto/Documents/workspace/third_party/kvrocks-controller/cmd/reader/reader-redis.service
        dest: /etc/systemd/system/reader.service
        mode: "0644"
        owner: root
        group: root

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

- name: Copy reader-rueidis service to nodes 10-14
  hosts: load_nodes_rueidis
  become: true
  tasks:
    - name: Copy reader-rueidis service to remote hosts
      ansible.builtin.copy:
        src: /Users/byron.seto/Documents/workspace/third_party/kvrocks-controller/cmd/reader/reader-rueidis.service
        dest: /etc/systemd/system/reader.service
        mode: "0644"
        owner: root
        group: root

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes
