[nodes]
; kvrocks-profile-lite-12.eu-central-1a ansible_host=127.0.0.1 ansible_port=10391
; kvrocks-profile-lite-13.eu-central-1a ansible_host=127.0.0.1 ansible_port=11471
; kvrocks-profile-lite-14.eu-central-1a ansible_host=127.0.0.1 ansible_port=11947
; kvrocks-profile-lite-15.eu-central-1a ansible_host=127.0.0.1 ansible_port=11095
; kvrocks-profile-lite-16.eu-central-1a ansible_host=127.0.0.1 ansible_port=10732
; kvrocks-profile-lite-17.eu-central-1a ansible_host=127.0.0.1 ansible_port=11030
; kvrocks-profile-lite-18.eu-central-1a ansible_host=127.0.0.1 ansible_port=10346
; kvrocks-profile-lite-19.eu-central-1a ansible_host=127.0.0.1 ansible_port=11375
; kvrocks-profile-lite-20.eu-central-1a ansible_host=127.0.0.1 ansible_port=10880
; kvrocks-profile-lite-21.eu-central-1a ansible_host=127.0.0.1 ansible_port=11245
; kvrocks-profile-lite-22.eu-central-1a ansible_host=127.0.0.1 ansible_port=13469
; kvrocks-profile-lite-23.eu-central-1a ansible_host=127.0.0.1 ansible_port=13486
; kvrocks-profile-lite-24.eu-central-1a ansible_host=127.0.0.1 ansible_port=13591

; kvrocks-profile-lite-30.us-east-1a ansible_host=127.0.0.1 ansible_port=13036 
kvrocks-profile-lite-31.us-east-1a ansible_host=127.0.0.1 ansible_port=11516 
kvrocks-profile-lite-32.us-east-1a ansible_host=127.0.0.1 ansible_port=11766 
kvrocks-profile-lite-33.us-east-1a ansible_host=127.0.0.1 ansible_port=12101 
kvrocks-profile-lite-34.us-east-1a ansible_host=127.0.0.1 ansible_port=12766 
kvrocks-profile-lite-35.us-east-1a ansible_host=127.0.0.1 ansible_port=11378 
kvrocks-profile-lite-36.us-east-1a ansible_host=127.0.0.1 ansible_port=11061 
kvrocks-profile-lite-37.us-east-1a ansible_host=127.0.0.1 ansible_port=11213 
kvrocks-profile-lite-38.us-east-1a ansible_host=127.0.0.1 ansible_port=12831 
kvrocks-profile-lite-39.us-east-1a ansible_host=127.0.0.1 ansible_port=12209 
kvrocks-profile-lite-40.us-east-1a ansible_host=127.0.0.1 ansible_port=11149 
kvrocks-profile-lite-41.us-east-1a ansible_host=127.0.0.1 ansible_port=12548 
kvrocks-profile-lite-42.us-east-1a ansible_host=127.0.0.1 ansible_port=11261 
kvrocks-profile-lite-43.us-east-1a ansible_host=127.0.0.1 ansible_port=10712 
kvrocks-profile-lite-44.us-east-1a ansible_host=127.0.0.1 ansible_port=10694 
kvrocks-profile-lite-45.us-east-1a ansible_host=127.0.0.1 ansible_port=12381 
kvrocks-profile-lite-46.us-east-1a ansible_host=127.0.0.1 ansible_port=10134 
kvrocks-profile-lite-47.us-east-1a ansible_host=127.0.0.1 ansible_port=10369 
kvrocks-profile-lite-48.us-east-1a ansible_host=127.0.0.1 ansible_port=10543 
kvrocks-profile-lite-49.us-east-1a ansible_host=127.0.0.1 ansible_port=11819 
kvrocks-profile-lite-50.us-east-1a ansible_host=127.0.0.1 ansible_port=12109 
kvrocks-profile-lite-51.us-east-1a ansible_host=127.0.0.1 ansible_port=11917 
kvrocks-profile-lite-52.us-east-1a ansible_host=127.0.0.1 ansible_port=12253 
kvrocks-profile-lite-53.us-east-1a ansible_host=127.0.0.1 ansible_port=10075 
kvrocks-profile-lite-54.us-east-1a ansible_host=127.0.0.1 ansible_port=11750 
kvrocks-profile-lite-55.us-east-1a ansible_host=127.0.0.1 ansible_port=12105 
kvrocks-profile-lite-56.us-east-1a ansible_host=127.0.0.1 ansible_port=11054 
kvrocks-profile-lite-57.us-east-1a ansible_host=127.0.0.1 ansible_port=10700 
kvrocks-profile-lite-58.us-east-1a ansible_host=127.0.0.1 ansible_port=11532 
kvrocks-profile-lite-59.us-east-1a ansible_host=127.0.0.1 ansible_port=10949 
kvrocks-profile-lite-60.us-east-1a ansible_host=127.0.0.1 ansible_port=12481 
kvrocks-profile-lite-61.us-east-1a ansible_host=127.0.0.1 ansible_port=11822 
kvrocks-profile-lite-62.us-east-1a ansible_host=127.0.0.1 ansible_port=12700 
kvrocks-profile-lite-63.us-east-1a ansible_host=127.0.0.1 ansible_port=13030 
kvrocks-profile-lite-64.us-east-1a ansible_host=127.0.0.1 ansible_port=12127 
kvrocks-profile-lite-65.us-east-1a ansible_host=127.0.0.1 ansible_port=12607 
kvrocks-profile-lite-66.us-east-1a ansible_host=127.0.0.1 ansible_port=12482 
kvrocks-profile-lite-67.us-east-1a ansible_host=127.0.0.1 ansible_port=12966 
kvrocks-profile-lite-68.us-east-1a ansible_host=127.0.0.1 ansible_port=11306 
kvrocks-profile-lite-69.us-east-1a ansible_host=127.0.0.1 ansible_port=10249 
kvrocks-profile-lite-70.us-east-1a ansible_host=127.0.0.1 ansible_port=12125 
kvrocks-profile-lite-71.us-east-1a ansible_host=127.0.0.1 ansible_port=10730 
kvrocks-profile-lite-72.us-east-1a ansible_host=127.0.0.1 ansible_port=11786 
kvrocks-profile-lite-73.us-east-1a ansible_host=127.0.0.1 ansible_port=10962 
kvrocks-profile-lite-74.us-east-1a   ansible_host=127.0.0.1 ansible_port=13232
kvrocks-profile-lite-75.us-east-1a   ansible_host=127.0.0.1 ansible_port=10721
kvrocks-profile-lite-76.us-east-1a   ansible_host=127.0.0.1 ansible_port=11019

; kvrocks-profile-lite-18.us-west-1a ansible_host=127.0.0.1 ansible_port=13300
; kvrocks-profile-lite-19.us-west-1a ansible_host=127.0.0.1 ansible_port=13299
; kvrocks-profile-lite-20.us-west-1a ansible_host=127.0.0.1 ansible_port=13337
; kvrocks-profile-lite-21.us-west-1a ansible_host=127.0.0.1 ansible_port=43331
; kvrocks-profile-lite-22.us-west-1a ansible_host=127.0.0.1 ansible_port=13334
; kvrocks-profile-lite-23.us-west-1a ansible_host=127.0.0.1 ansible_port=13282
; kvrocks-profile-lite-24.us-west-1a ansible_host=127.0.0.1 ansible_port=13269
; kvrocks-profile-lite-25.us-west-1a ansible_host=127.0.0.1 ansible_port=12114
; kvrocks-profile-lite-26.us-west-1a ansible_host=127.0.0.1 ansible_port=13222
; kvrocks-profile-lite-27.us-west-1a ansible_host=127.0.0.1 ansible_port=13294
; kvrocks-profile-lite-28.us-west-1a ansible_host=127.0.0.1 ansible_port=13348
; kvrocks-profile-lite-29.us-west-1a ansible_host=127.0.0.1 ansible_port=13298
; kvrocks-profile-lite-30.us-west-1a ansible_host=127.0.0.1 ansible_port=13247
; kvrocks-profile-lite-31.us-west-1a ansible_host=127.0.0.1 ansible_port=13332
; kvrocks-profile-lite-32.us-west-1a ansible_host=127.0.0.1 ansible_port=13288
; kvrocks-profile-lite-33.us-west-1a ansible_host=127.0.0.1 ansible_port=13208
; kvrocks-profile-lite-34.us-west-1a ansible_host=127.0.0.1 ansible_port=13383
; kvrocks-profile-lite-35.us-west-1a ansible_host=127.0.0.1 ansible_port=13051
; kvrocks-profile-lite-36.us-west-1a ansible_host=127.0.0.1 ansible_port=13350
; kvrocks-profile-lite-37.us-west-1a ansible_host=127.0.0.1 ansible_port=13064
; kvrocks-profile-lite-38.us-west-1a ansible_host=127.0.0.1 ansible_port=13226
; kvrocks-profile-lite-39.us-west-1a ansible_host=127.0.0.1 ansible_port=13236
; kvrocks-profile-lite-40.us-west-1a ansible_host=127.0.0.1 ansible_port=13217
; kvrocks-profile-lite-41.us-west-1a ansible_host=127.0.0.1 ansible_port=13212
; kvrocks-profile-lite-42.us-west-1a ansible_host=127.0.0.1 ansible_port=10412

; kvrocks-profile-lite-14.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=12544
; kvrocks-profile-lite-15.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13050
; kvrocks-profile-lite-16.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13045
; kvrocks-profile-lite-17.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=12680
; kvrocks-profile-lite-18.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13052
; kvrocks-profile-lite-19.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=12678
; kvrocks-profile-lite-20.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13040
; kvrocks-profile-lite-21.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13035
; kvrocks-profile-lite-22.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13024
; kvrocks-profile-lite-23.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13028
; kvrocks-profile-lite-24.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13176
; kvrocks-profile-lite-25.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13170



[nodes:vars]
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PreferredAuthentications=publickey,password -o PubkeyAuthentication=yes'
ansible_scp_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_sftp_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'   

# for debugging
# ANSIBLE_DEBUG=1 ansible -i ansible-load-nodes.ini load_nodes -a "echo hello"
