[nodes]
; kvrocks-profile-lite-12.eu-central-1a ansible_host=127.0.0.1 ansible_port=10391
; kvrocks-profile-lite-13.eu-central-1a ansible_host=127.0.0.1 ansible_port=11471
; kvrocks-profile-lite-14.eu-central-1a ansible_host=127.0.0.1 ansible_port=11947
; kvrocks-profile-lite-15.eu-central-1a ansible_host=127.0.0.1 ansible_port=11095
; kvrocks-profile-lite-16.eu-central-1a ansible_host=127.0.0.1 ansible_port=10732
; kvrocks-profile-lite-17.eu-central-1a ansible_host=127.0.0.1 ansible_port=11030
; kvrocks-profile-lite-18.eu-central-1a ansible_host=127.0.0.1 ansible_port=10346
; kvrocks-profile-lite-19.eu-central-1a ansible_host=127.0.0.1 ansible_port=11375
; kvrocks-profile-lite-20.eu-central-1a ansible_host=127.0.0.1 ansible_port=10880
; kvrocks-profile-lite-21.eu-central-1a ansible_host=127.0.0.1 ansible_port=11245
; kvrocks-profile-lite-22.eu-central-1a ansible_host=127.0.0.1 ansible_port=13469
; kvrocks-profile-lite-23.eu-central-1a ansible_host=127.0.0.1 ansible_port=13486
; kvrocks-profile-lite-24.eu-central-1a ansible_host=127.0.0.1 ansible_port=13591

kvrocks-profile-lite-30.us-east-1a ansible_host=127.0.0.1 ansible_port=13036 
kvrocks-profile-lite-31.us-east-1a ansible_host=127.0.0.1 ansible_port=11516 
kvrocks-profile-lite-32.us-east-1a ansible_host=127.0.0.1 ansible_port=11766 
kvrocks-profile-lite-33.us-east-1a ansible_host=127.0.0.1 ansible_port=12101 
kvrocks-profile-lite-34.us-east-1a ansible_host=127.0.0.1 ansible_port=12766 
kvrocks-profile-lite-35.us-east-1a ansible_host=127.0.0.1 ansible_port=11378 
kvrocks-profile-lite-36.us-east-1a ansible_host=127.0.0.1 ansible_port=11061 
kvrocks-profile-lite-37.us-east-1a ansible_host=127.0.0.1 ansible_port=11213 
kvrocks-profile-lite-38.us-east-1a ansible_host=127.0.0.1 ansible_port=12831 
kvrocks-profile-lite-39.us-east-1a ansible_host=127.0.0.1 ansible_port=12209 
kvrocks-profile-lite-40.us-east-1a ansible_host=127.0.0.1 ansible_port=11149 
kvrocks-profile-lite-41.us-east-1a ansible_host=127.0.0.1 ansible_port=12548 
kvrocks-profile-lite-42.us-east-1a ansible_host=127.0.0.1 ansible_port=11261 
kvrocks-profile-lite-43.us-east-1a ansible_host=127.0.0.1 ansible_port=10712 
kvrocks-profile-lite-44.us-east-1a ansible_host=127.0.0.1 ansible_port=10694 
kvrocks-profile-lite-45.us-east-1a ansible_host=127.0.0.1 ansible_port=12381 
kvrocks-profile-lite-46.us-east-1a ansible_host=127.0.0.1 ansible_port=10134 
kvrocks-profile-lite-47.us-east-1a ansible_host=127.0.0.1 ansible_port=10369 
kvrocks-profile-lite-48.us-east-1a ansible_host=127.0.0.1 ansible_port=10543 
kvrocks-profile-lite-49.us-east-1a ansible_host=127.0.0.1 ansible_port=11819 
kvrocks-profile-lite-50.us-east-1a ansible_host=127.0.0.1 ansible_port=12109 
kvrocks-profile-lite-51.us-east-1a ansible_host=127.0.0.1 ansible_port=11917 
kvrocks-profile-lite-52.us-east-1a ansible_host=127.0.0.1 ansible_port=12253 
kvrocks-profile-lite-53.us-east-1a ansible_host=127.0.0.1 ansible_port=10075 
kvrocks-profile-lite-54.us-east-1a ansible_host=127.0.0.1 ansible_port=11750 
kvrocks-profile-lite-55.us-east-1a ansible_host=127.0.0.1 ansible_port=12105 
kvrocks-profile-lite-56.us-east-1a ansible_host=127.0.0.1 ansible_port=11054 
kvrocks-profile-lite-57.us-east-1a ansible_host=127.0.0.1 ansible_port=10700 
kvrocks-profile-lite-58.us-east-1a ansible_host=127.0.0.1 ansible_port=11532 
kvrocks-profile-lite-59.us-east-1a ansible_host=127.0.0.1 ansible_port=10949 
kvrocks-profile-lite-60.us-east-1a ansible_host=127.0.0.1 ansible_port=12481 
kvrocks-profile-lite-61.us-east-1a ansible_host=127.0.0.1 ansible_port=11822 
kvrocks-profile-lite-62.us-east-1a ansible_host=127.0.0.1 ansible_port=12700 
kvrocks-profile-lite-63.us-east-1a ansible_host=127.0.0.1 ansible_port=13030 
kvrocks-profile-lite-64.us-east-1a ansible_host=127.0.0.1 ansible_port=12127 
kvrocks-profile-lite-65.us-east-1a ansible_host=127.0.0.1 ansible_port=12607 
kvrocks-profile-lite-66.us-east-1a ansible_host=127.0.0.1 ansible_port=12482 
kvrocks-profile-lite-67.us-east-1a ansible_host=127.0.0.1 ansible_port=12966 
kvrocks-profile-lite-68.us-east-1a ansible_host=127.0.0.1 ansible_port=11306 
kvrocks-profile-lite-69.us-east-1a ansible_host=127.0.0.1 ansible_port=10249 
kvrocks-profile-lite-70.us-east-1a ansible_host=127.0.0.1 ansible_port=12125 
kvrocks-profile-lite-71.us-east-1a ansible_host=127.0.0.1 ansible_port=10730 
kvrocks-profile-lite-72.us-east-1a ansible_host=127.0.0.1 ansible_port=11786 
kvrocks-profile-lite-73.us-east-1a ansible_host=127.0.0.1 ansible_port=10962 
kvrocks-profile-lite-74.us-east-1a ansible_host=127.0.0.1 ansible_port=13232
kvrocks-profile-lite-75.us-east-1a ansible_host=127.0.0.1 ansible_port=10721
kvrocks-profile-lite-76.us-east-1a ansible_host=127.0.0.1 ansible_port=11019

; kvrocks-profile-lite-18.us-west-1a ansible_host=127.0.0.1 ansible_port=13300
; kvrocks-profile-lite-19.us-west-1a ansible_host=127.0.0.1 ansible_port=13299
; kvrocks-profile-lite-20.us-west-1a ansible_host=127.0.0.1 ansible_port=13337
; kvrocks-profile-lite-21.us-west-1a ansible_host=127.0.0.1 ansible_port=43331
; kvrocks-profile-lite-22.us-west-1a ansible_host=127.0.0.1 ansible_port=13334
; kvrocks-profile-lite-23.us-west-1a ansible_host=127.0.0.1 ansible_port=13282
; kvrocks-profile-lite-24.us-west-1a ansible_host=127.0.0.1 ansible_port=13269
; kvrocks-profile-lite-25.us-west-1a ansible_host=127.0.0.1 ansible_port=12114
; kvrocks-profile-lite-26.us-west-1a ansible_host=127.0.0.1 ansible_port=13222
; kvrocks-profile-lite-27.us-west-1a ansible_host=127.0.0.1 ansible_port=13294
; kvrocks-profile-lite-28.us-west-1a ansible_host=127.0.0.1 ansible_port=13348
; kvrocks-profile-lite-29.us-west-1a ansible_host=127.0.0.1 ansible_port=13298
; kvrocks-profile-lite-30.us-west-1a ansible_host=127.0.0.1 ansible_port=13247
; kvrocks-profile-lite-31.us-west-1a ansible_host=127.0.0.1 ansible_port=13332
; kvrocks-profile-lite-32.us-west-1a ansible_host=127.0.0.1 ansible_port=13288
; kvrocks-profile-lite-33.us-west-1a ansible_host=127.0.0.1 ansible_port=13208
; kvrocks-profile-lite-34.us-west-1a ansible_host=127.0.0.1 ansible_port=13383
; kvrocks-profile-lite-35.us-west-1a ansible_host=127.0.0.1 ansible_port=13051
; kvrocks-profile-lite-36.us-west-1a ansible_host=127.0.0.1 ansible_port=13350
; kvrocks-profile-lite-37.us-west-1a ansible_host=127.0.0.1 ansible_port=13064
; kvrocks-profile-lite-38.us-west-1a ansible_host=127.0.0.1 ansible_port=13226
; kvrocks-profile-lite-39.us-west-1a ansible_host=127.0.0.1 ansible_port=13236
; kvrocks-profile-lite-40.us-west-1a ansible_host=127.0.0.1 ansible_port=13217
; kvrocks-profile-lite-41.us-west-1a ansible_host=127.0.0.1 ansible_port=13212
; kvrocks-profile-lite-42.us-west-1a ansible_host=127.0.0.1 ansible_port=10412

; |-------|------------------------------------------|--------------------|--------|-----------|
; | SHARD |                 NODE ID                  |      ADDRESS       |  ROLE  | MIGRATING |
; |-------|------------------------------------------|--------------------|--------|-----------|
; |     0 | VM98ROf7DH9FxnNKIW2e9rVKv49UYugVRLr9jBuW | 172.30.77.133:6379 | MASTER | NO        |
; |     1 | Fv9N4pOFBTS8QhAbYCllCwDBtcgtFYBlmx75q8Nt | 172.30.93.111:6379 | MASTER | NO        |
; |     2 | 0Kr0Rl47gNxmXHpgcA1BubiENJho6HYkfJ5ZFpkR | 172.30.66.110:6379 | MASTER | NO        |
; |     3 | mZkXY4zSfLNOTIFecLUHeRGNAyOqQshPjhZMn2eU | 172.30.69.200:6379 | MASTER | NO        |
; |     4 | igaSNvfTX0flnabEoPTuCSNtdhZt0fkOz8Nj55ZA | 172.30.64.13:6379  | MASTER | NO        |
; |     5 | jPt6McjMx9bOvR6xw0z0hViGNyxG5a70472o2bEa | 172.30.76.164:6379 | MASTER | NO        |
; |     6 | 04uNR2kfV6mvt6QgpVAOhE7WFFFzWpeoxSK03tzq | 172.30.81.42:6379  | MASTER | NO        |
; |     7 | 2G9M1UpTvp7QS1CokBy9CWcubC32sIGd1u1G0qNu | 172.30.65.108:6379 | MASTER | NO        |
; |     8 | mgRy5vz8OMvKcvgoZQgbFIp6JwybhBZiG0bhR0cG | 172.30.75.232:6379 | MASTER | NO        |
; |     9 | 2ScALEDbAYBfbNpJXRwvxdKJqgw1dUbbUCtVrmCc | 172.30.68.126:6379 | MASTER | NO        |
; |    10 | m2UlcMyoUUBeJQYjlNheom0veO2ygTBvooGZtDXr | 172.30.71.164:6379 | MASTER | NO        |
; |    11 | m4QNSM4ywDFb1mC4LpZmb1rCOFoZVzU2tr3XK0oU | 172.30.89.105:6379 | MASTER | NO        |
; |    12 | dBsHuq91rfcOFucLGQrj8ppuPZmdjo7TBeMVonjn | 172.30.75.139:6379 | MASTER | NO        |
; |    13 | fNhyR7WuTE0IBuMScqdN0ev7VdbKgAXm4jLTyzOe | 172.30.69.46:6379  | MASTER | NO        |
; |    14 | PoqgmCX3L3xQKApbTmmFT13LyqJaao6Dn7UqG0je | 172.30.71.57:6379  | MASTER | NO        |
; |    15 | rksnONieb40uTzfHk4jjZOvKkYmuXpI2zspjvfdj | 172.30.67.156:6379 | MASTER | NO        |
; |    16 | LmeDjDU1B8v9QhCjfatOw2HEGukdhPMXu0uSrHhw | 172.30.72.207:6379 | MASTER | NO        |
; |    17 | mMastDY0crUiDfZdWqtJoxCleheS0ZwwQ7X6s12z | 172.30.85.223:6379 | MASTER | NO        |
; |    18 | IZB69ypbsWGGYWuIAVPetuTYo751aWycZ9z0iamY | 172.30.95.191:6379 | MASTER | NO        |
; |    19 | TNnJihA3k03qHzBRotJSZXz1lEAuHh8lublNKPng | 172.30.84.109:6379 | MASTER | NO        |
; |    20 | DNCW6xf1ee4y7E23ToUklVztTWpvyb46HiE80HZv | 172.30.77.90:6379  | MASTER | NO        |
; |    21 | gkVatJyzchtyQeKQ1LkisdJvF7RI9q05TTaoazAe | 172.30.89.89:6379  | MASTER | NO        |
; |    22 | cbqBXWqNAjlWKNFog5d8lyHWZ4RCRsHZbRdvHKfq | 172.30.91.139:6379 | MASTER | NO        |
; |    23 | X5Iif2gAKCmVsi3BHAcdL32q1imNOHOzqiukf3Mn | 172.30.95.175:6379 | MASTER | NO        |
; |    24 | MxQ9xPkQoLfU3JSVICcpVVVGLTawPonj9uVoH09h | 172.30.68.166:6379 | MASTER | NO        |
; |    25 | YDAcU3srM7d6iMyOX44rIuKp59fUEM9IoA0t49gv | 172.30.95.247:6379 | MASTER | NO        |
; |    26 | i7yZWYeTwo1reuVEQlidR57b41GNkf18NwHvnRDr | 172.30.82.74:6379  | MASTER | NO        |
; |    27 | GP9hDpeVSOkne8J9mTKzGJcGDh42TiwrsLDyAPPH | 172.30.93.235:6379 | MASTER | NO        |
; |    28 | skRCcGAVrTSJWQZuX0EMTBpraqiHcaRRcSwcrtOw | 172.30.92.246:6379 | MASTER | NO        |
; |    29 | 3evYjrs8hsadClVeuIFKboaA33Vemh4xQmbAhQbI | 172.30.88.28:6379  | MASTER | NO        |
; |    30 | 20zfuL34r6K6uqPK1daOWtENLn1CkH4C1OnLvALe | 172.30.91.167:6379 | MASTER | NO        |
; |    31 | o3hWcdC8FXCPJA9fiLECKSVSAmzEKdQuKi3dUIGb | 172.30.93.172:6379 | MASTER | NO        |
; |    32 | 5lhB9LSKwVk1ie0dswnPTgb7bFcAbVMfAQecohx0 | 172.30.95.12:6379  | MASTER | NO        |
; |    33 | 07vzQXoIXyYC3hST8xkQGc4XjKb0quZfZazI8dFj | 172.30.92.72:6379  | MASTER | NO        |
; |    34 | tRiA04GRsEGGndUityvmvQOQmCLwKELDlHt1j9kP | 172.30.69.15:6379  | MASTER | NO        |
; |    35 | IdSNJ5oKutd3za127sHy4eojfu77sm9797YL67Tb | 172.30.88.118:6379 | MASTER | NO        |
; |    36 | F6fJJ7dK9FZRpLkkMHKQW1178yDW5rJYPINF60is | 172.30.95.118:6379 | MASTER | NO        |
; |    37 | ejr9jJ0nrjzlblxSpRAsI3Xln6trdWasaKK10HkI | 172.30.66.157:6379 | MASTER | NO        |
; |    38 | Co4TmXl00BfAefEhLx8HTb905iUY3dFOn0O2xVkw | 172.30.84.92:6379  | MASTER | NO        |
; |    39 | Vb8qU9iXeAnuRUR7WhVp0vvMArZpO47QgSoO08JB | 172.30.94.91:6379  | MASTER | NO        |
; |    40 | oI1fgCtbOky33iBcN9ko36pZHcsdi2QEBTh546LB | 172.30.66.125:6379 | MASTER | NO        |
; |    41 | Vo1o6NYHAEyYVlgIqTq8O7msnBieYDSk99payPs4 | 172.30.85.81:6379  | MASTER | NO        |
; |    42 | JPurQbrFcDUaULqDQsvExCI0gEB9WKipZ6gYl5Jf | 172.30.95.9:6379   | MASTER | NO        |
; |    43 | YMbEofmkD0JyNlBtyXi33uwZJSYZPU6v0FMvDkKL | 172.30.84.230:6379 | MASTER | NO        |
; |-------|------------------------------------------|--------------------|--------|-----------|


; kvrocks-profile-lite-14.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=12544
; kvrocks-profile-lite-15.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13050
; kvrocks-profile-lite-16.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13045
; kvrocks-profile-lite-17.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=12680
; kvrocks-profile-lite-18.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13052
; kvrocks-profile-lite-19.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=12678
; kvrocks-profile-lite-20.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13040
; kvrocks-profile-lite-21.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13035
; kvrocks-profile-lite-22.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13024
; kvrocks-profile-lite-23.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13028
; kvrocks-profile-lite-24.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13176
; kvrocks-profile-lite-25.ap-southeast-1a  ansible_host=127.0.0.1 ansible_port=13170



[nodes:vars]
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PreferredAuthentications=publickey,password -o PubkeyAuthentication=yes'
ansible_scp_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_sftp_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'   

# for debugging
# ANSIBLE_DEBUG=1 ansible -i ansible-load-nodes.ini load_nodes -a "echo hello"
