[load_nodes]
kvrocks-byron-load-test-node-10.us-east-1a ansible_host=127.0.0.1 ansible_port=13642
kvrocks-byron-load-test-node-11.us-east-1a ansible_host=127.0.0.1 ansible_port=13638
kvrocks-byron-load-test-node-12.us-east-1a ansible_host=127.0.0.1 ansible_port=11752
kvrocks-byron-load-test-node-13.us-east-1a ansible_host=127.0.0.1 ansible_port=13672
kvrocks-byron-load-test-node-14.us-east-1a ansible_host=127.0.0.1 ansible_port=13677
kvrocks-byron-load-test-node-5.us-east-1a ansible_host=127.0.0.1 ansible_port=13633
kvrocks-byron-load-test-node-6.us-east-1a ansible_host=127.0.0.1 ansible_port=13697
kvrocks-byron-load-test-node-7.us-east-1a ansible_host=127.0.0.1 ansible_port=10523
kvrocks-byron-load-test-node-8.us-east-1a ansible_host=127.0.0.1 ansible_port=13667
kvrocks-byron-load-test-node-9.us-east-1a ansible_host=127.0.0.1 ansible_port=13623

[load_nodes:vars]
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PreferredAuthentications=publickey,password -o PubkeyAuthentication=yes'
ansible_scp_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_sftp_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'   

# for debugging
# ANSIBLE_DEBUG=1 ansible -i ansible-load-nodes.ini load_nodes -a "echo hello"
