[load_nodes]
# kvrocks-byron-load-test-node-1.us-east-1a ansible_host=127.0.0.1 ansible_port=13538 # will use as a dedicated writer
kvrocks-byron-load-test-node-10.us-east-1a ansible_host=127.0.0.1 ansible_port=12519
kvrocks-byron-load-test-node-11.us-east-1a ansible_host=127.0.0.1 ansible_port=10777
kvrocks-byron-load-test-node-12.us-east-1a ansible_host=127.0.0.1 ansible_port=13170
kvrocks-byron-load-test-node-13.us-east-1a ansible_host=127.0.0.1 ansible_port=13038
kvrocks-byron-load-test-node-14.us-east-1a ansible_host=127.0.0.1 ansible_port=13002
kvrocks-byron-load-test-node-2.us-east-1a ansible_host=127.0.0.1 ansible_port=11613
kvrocks-byron-load-test-node-3.us-east-1a ansible_host=127.0.0.1 ansible_port=13633
kvrocks-byron-load-test-node-4.us-east-1a ansible_host=127.0.0.1 ansible_port=12186
kvrocks-byron-load-test-node-5.us-east-1a ansible_host=127.0.0.1 ansible_port=11648
kvrocks-byron-load-test-node-6.us-east-1a ansible_host=127.0.0.1 ansible_port=12254
kvrocks-byron-load-test-node-7.us-east-1a ansible_host=127.0.0.1 ansible_port=10013
kvrocks-byron-load-test-node-8.us-east-1a ansible_host=127.0.0.1 ansible_port=10041
kvrocks-byron-load-test-node-9.us-east-1a ansible_host=127.0.0.1 ansible_port=13087

[load_nodes:vars]
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PreferredAuthentications=publickey,password -o PubkeyAuthentication=yes'
ansible_scp_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_sftp_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'   

# for debugging
# ANSIBLE_DEBUG=1 ansible -i ansible-load-nodes.ini load_nodes -a "echo hello"
